name: ci-integration-tests

on:
  workflow_run:
    workflows: 
      - "ci-unit-tests"       # Trigger after the "ci-unit-tests" workflow
    types:
      - completed

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      # Start the authentication service for testing
      authentication_service:
        image: biostech/rental-authentication-service:1.0.0
        env:  # Use `env` to pass secrets as environment variables
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_TYPE: ${{ secrets.DATABASE_TYPE }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_SSLMODE: ${{ secrets.DATABASE_SSLMODE }}
          DATABASE_TIMEZONE: ${{ secrets.DATABASE_TIMEZONE }}
          DATABASE_CONNECT_TIMEOUT: ${{ secrets.DATABASE_CONNECT_TIMEOUT }}
          
    steps:
      - uses: actions/checkout@v4  # Checkout code

      - name: Set up Go
        uses: actions/setup-go@v4  # Set up Go environment
        with:
          go-version: '1.21.0'

      - name: Wait for Auth Service
        run: |
          # Ensure auth service is ready
          echo "Waiting for authentication service to be ready..."
          until curl -s http://authentication-service/healthz; do
            echo "Auth service not ready. Retrying in 5 seconds..."
            sleep 5
          done
          echo "Auth service is ready!"

      - name: Run Integration Tests
        env:
          AUTH_URL: "http://authentication-service/api/v1/authentication/"
        run: make integration-test  # Run integration tests
